name: Publish top PyPI
on: push

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install
      run: python -m pip install build --user
    - name: Build binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}